### ISSUE TITLE
Unable to setup registry stack: 502 Bad Gateway

### ISSUE THREAD

**Issue by danawoodman** [rancher/community-catalog#40]
Hello, 

Trying to get the "registry" stack working but not able to. I'm hitting a 502 Bad Gateway NGINX error when connecting to https://registry.mydomain.com. 

I configured the stack to use `registry.mydomain.com` as the FQDN and used the default ports (`5000`/`443`). 

Here is my `docker-compose.yml`:

``` yaml
db:
  environment:
    MYSQL_DATABASE: portus
    MYSQL_PASSWORD: mypasswordhere
    MYSQL_ROOT_PASSWORD: mypasswordhere
    MYSQL_USER: portus
  labels:
    io.rancher.service.hash: 1e0b6e32ffafa0a0b0b9250e7540d97fe5fdce9d
  tty: true
  image: mysql:5.7.10
  volumes:
  - /var/docker-registry/db:/var/lib/mysql
  stdin_open: true
sslproxy:
  labels:
    io.rancher.service.hash: d12f9cfbe6ef4cf67459c96af4096fd7d4feb0c4
  tty: true
  image: nginx:1.9.9
  links:
  - portus:portus
  volumes:
  - /var/docker-registry/certs:/etc/nginx/certs:ro
  - /var/docker-registry/proxy:/etc/nginx/conf.d:ro
  stdin_open: true
lb:
  ports:
  - 5000:5000/tcp
  - 443:443/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:not_host_label: lb=0
    io.rancher.loadbalancer.target.sslproxy: 443=443
    io.rancher.service.hash: d7d36fab64ca84d9c4967ea01f47bff1ee5343f4
    io.rancher.loadbalancer.target.registry: 5000=5000
  tty: true
  image: rancher/load-balancer-service
  links:
  - registry:registry
  - sslproxy:sslproxy
  stdin_open: true
registry:
  environment:
    REGISTRY_AUTH_TOKEN_ISSUER: registry.mydomain.com
    REGISTRY_AUTH_TOKEN_REALM: https://registry.mydomain.com:443/v2/token
    REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry.crt
    REGISTRY_AUTH_TOKEN_SERVICE: registry.mydomain.com:5000
    REGISTRY_HTTP_SECRET: httpsecret
    REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
    REGISTRY_HTTP_TLS_KEY: /certs/registry.key
    REGISTRY_LOG_LEVEL: warn
    REGISTRY_NOTIFICATIONS_ENDPOINTS: |
      - name: portus
        url: http://portus:3000/v2/webhooks/events
        timeout: 500
        threshold: 5
        backoff: 1
    REGISTRY_STORAGE_DELETE_ENABLED: 'true'
  labels:
    io.rancher.service.hash: 6eccbc547093b7269e5f2abc71829a027ff43a65
  tty: true
  image: registry:2.1
  links:
  - portus:portus
  volumes:
  - /var/docker-registry/certs:/certs:ro
  - /var/docker-registry/data:/var/lib/registry
  stdin_open: true
portus:
  environment:
    PORTUS_CHECK_SSL_USAGE_ENABLED: 'true'
    PORTUS_GRAVATAR_ENABLED: 'true'
    PORTUS_KEY_PATH: /certs/registry.key
    PORTUS_LDAP_AUTHENTICATION_BIND_DN: ou=portus,dc=company,dc=com
    PORTUS_LDAP_AUTHENTICATION_ENABLED: 'false'
    PORTUS_LDAP_AUTHENTICATION_PASSWORD: password
    PORTUS_LDAP_BASE: ou=People,dc=company,dc=com
    PORTUS_LDAP_ENABLED: 'false'
    PORTUS_LDAP_GUESS_EMAIL_ATTR: mail
    PORTUS_LDAP_GUESS_EMAIL_ENABLED: 'true'
    PORTUS_LDAP_HOSTNAME: ldap.company.com
    PORTUS_LDAP_METHOD: starttls
    PORTUS_LDAP_PORT: '389'
    PORTUS_LDAP_UID: cn
    PORTUS_MACHINE_FQDN: registry.mydomain.com
    PORTUS_PASSWORD: mypasswordhere
    PORTUS_PORT: '443'
    PORTUS_PRODUCTION_DATABASE: portus
    PORTUS_PRODUCTION_HOST: db
    PORTUS_PRODUCTION_PASSWORD: mypasswordhere
    PORTUS_PRODUCTION_USERNAME: portus
    PORTUS_SECRET_KEY_BASE: mypasswordhere
    PORTUS_SMTP_ENABLED: 'false'
    REGISTRY_HOSTNAME: registry.mydomain.com
    REGISTRY_NAME: Registry
    REGISTRY_PORT: '5000'
    REGISTRY_SSL_ENABLED: 'true'
  labels:
    io.rancher.container.pull_image: always
    io.rancher.service.hash: efe4408dc0c6702a602249112ddc49d184f133ef
  tty: true
  image: sshipway/portus:2.0.3
  links:
  - db:db
  volumes:
  - /var/docker-registry/certs:/certs
  - /var/docker-registry/proxy:/etc/nginx/conf.d
  stdin_open: true
```

Here is my `rancher-compose.yml`:

``` yaml
db:
  scale: 1
  metadata:
    io.rancher.service.hash: d207d194d16104535c1df27c1c9ac5918b7cfa26
sslproxy:
  scale: 1
  metadata:
    io.rancher.service.hash: 76d82b9309a25e5460531ac297525a19e5a6ee54
lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
  metadata:
    io.rancher.service.hash: 71d8a2cfdb029771cf96cc7b5db9316380fd730b
registry:
  scale: 1
  metadata:
    io.rancher.service.hash: c2f7cdf5184286537044b64fbb51f0c0e574e30e
portus:
  scale: 1
  metadata:
    io.rancher.service.hash: 70cf70f82cd8b2af5a2c2b7ec7e4f8ab49cde759
```

Am I doing something wrong?

Thanks for any tips

**Comment by shethchintan7** [comment]
I'm facing the same issue. Can you check your protus logs does it say

`Access denied for user 'portus'@'10.42.115.220' (using password: YES)Please provide the root password for your MySQL installation`

**Comment by shobull** [comment]
Hi,

I have the same problem. Registry v2.3.1-3.0 from Catalog in Rancher v1.0.1.

**Comment by sshipway** [comment]
When the mysql container is started for the first time, it should create the (empty) database, set the root password, and create the portus user with the specified password.  Once the database exists, no further password changes are made.  So, it should be able to connect without issue if built from the template as the password is set in both containers...

I will run some more tests here and see if I can duplicate it.  It may be down to the inter-host networking issues that sometimes appear between Rancher Hosts under certain versions of Docker (1.9 and CoreOS?)

**Comment by sshipway** [comment]
I've tried, but I'm unable to duplicate this.  It may be down to the cross-host networking issue.
I have an updated Registry template awaiting approval that will
- Update to using the 2.0.5 image (which handles multi-homes containers)
- Add soft affinity between portus and mysql containers, to avoid networking issues
Hopefully this will solve things.  You can test the new version early by adding the Catalogue at
https://github.com/sshipway/community-catalog  and using the Registry template from there

**Comment by shobull** [comment]
I tried sshipway's community catalog with same results:
`Access denied for user 'portus'@'194.213.202.244' (using password: YES)Please provide the root password for your MySQL installation` (actually it is strange IP because it is not IP of Portus container or server).

- I'm using just one host running Docker v1.10.3. 
- I logged into 'portus' container and tried manual login (commandline tool 'mysql') with username 'portus' and got 'Access denied...'.
- I logged into 'db' container and manual login with username 'portus' worked ok. I also checked 'SHOW GRANTS FOR CURRENT_USER;'. It showed me that rights for 'portus' user are set up well (access allowed to "portus.*" and user "portus@%").

It looks like some problem with communication between containers.

**Comment by sshipway** [comment]
I notice you're using Docker 1.10.3 -- is this with CoreOS Beta?  I've tried using CoreOS Beta here with Rancher and it seems to have cross-host networking issues; I've reverted to using CoreOS Stable (Docker 1.9.1) on all Hosts and the Rancher server, and problems seemed to clear up.

The other possibility I considered is that you have your local DNS set up differently, and within the portus container, 'db' is not resolving to the MySQL container but to something external in your domain.  The error message you give is odd because I would have expected the connection to be coming from the Rancher subnet address of the Portus container (10.42.x.x). I'm wondering if you're not connecting to what you think you're connecting to.

**Comment by shobull** [comment]
I feel really stupid now. I found out that there is really dns name 'db' registered in our company with mysql installed. I was totally confused because last month everything worked ('db' dns record was set up few days ago).

I'm really sorry for this.

**Comment by sshipway** [comment]
This is a good reminder to people making template/stacks to use less common aliases when mapping containers in order to avoid this sort of confusion.  I should probably have called the link "registry-db-map" or similar; I had thought that these map names took priority over DNS.
Glad to hear it is all working now.

**Comment by sshipway** [comment]
"Invalid gateway" issues are when the Portus container has not started correctly, usually due to database connection issues which are probably down to the naming issue above or inter-host communication issues (fixed by the affinity rules in the latest template).

I think this is all fixed in the latest `sshipway/portus:2.0.5` container and template version, so this can be closed.

**Comment by EugenMayer** [comment]
The issue is, as described in , that you missed to wait for the database, implemented it here https://github.com/EugenMayer/portus-build/blob/master/build/startup.sh#L37 just pick it for your registry

You might even think about using this portus build i general. I created it based on your goals, but using the current build of portus without modifying the source of portus. You current portus build is about 230 commits behind, missing one very important feature: deleting tags and images using portus.

This portus image should be compatible with your registry build out of the box, i used it here https://github.com/EugenMayer/kontextwork-catalog/tree/master/templates/registry-slim - maybe just compare the ENVs ( but i mostly sticked to yours )

**Comment by sshipway** [comment]
@EugenMayer -- as long as you preserved the startup.sh, changed Dockerfile, and the additional rake tasks (used to initialise the Repository definition in a virgin database) then all should work.

These were the only changes I made (there was also a fix for registry queries in certain cases, but that has been merged back into the main codebase)

**Comment by rawmind0** [comment]
Current version working.

Please, reopen if you still have the issue.
